# Generated by Django 2.2 on 2019-04-12 16:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.CharField(max_length=200)),
                ('_id', models.CharField(max_length=24)),
                ('location', django.contrib.gis.db.models.fields.PointField(
                    blank=True, null=True, srid=4326)),
                ('email', models.EmailField(max_length=200)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
