# Generated by Django 2.2 on 2019-04-12 15:57

from django.db import migrations
import json
from django.contrib.gis.geos import Point
from pathlib import Path


class Migration(migrations.Migration):

    def load_data(apps, schema_editor):
        '''
        The json data looks like this:
        {
            "name": "Adornica",
            "picture": "http://placehold.it/150x150",
            "_id": "5a0c6bd5fd3eb67969316e00",
            "location": {
                "coordinates": [
                    -6.77999,
                    33.84045
                ],
                "type": "Point"
            },
            "email": "leilaware@adornica.com",
            "city": "Rabat"
        }
        '''

        DATA_FILE = "shops.json"
        Shop = apps.get_model('shops', 'Shops')
        jsonfile = Path(__file__).parent / DATA_FILE

        with open(str(jsonfile)) as datafile:
            objects = json.load(datafile)
            for obj in objects:
                try:
                    name = obj['name']
                    picture = obj['picture']
                    _id = obj['_id']
                    lon = obj['location']['coordinates'][0]
                    lat = obj['location']['coordinates'][1]
                    location = Point(lon, lat)
                    email = obj['email']
                    city = obj['city']
                    Shop(name=name, picture=picture, _id=_id,
                         location=location, email=email, city=city).save()
                except KeyError:
                    pass

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
