# Generated by Django 2.2 on 2019-04-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20190412_1837'),
        ('custom_user', '0005_auto_20190415_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='likes',
            field=models.ManyToManyField(to='shops.Shops'),
        ),
    ]
